- name: sshd_config
  ansible.builtin.copy:
    src: files/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '644'
  notify: reload ssh daemon
  become: yes
# To Confirm, in vm, cat /etc/ssh/sshd_config should be the same as files/sshd_config
