name: Build, Push to Dockerhub and Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/task-tracker:latest .

      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/task-tracker:latest

      - name: Copy SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/winston-aws-vm-key
          chmod 600 ~/.ssh/winston-aws-vm-key

      - name: Copy docker-compose file
        run: |
          ssh -i ~/.ssh/winston-aws-vm-key -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} -t "sudo mkdir -p ~/services/task-tracker && sudo chown -R ${{ secrets.EC2_USER }}:${{ secrets.EC2_USER }} /home/${{ secrets.EC2_USER }}/services"
          scp -i ~/.ssh/winston-aws-vm-key -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/services/task-tracker/docker-compose.yml

      - name: SSH and deploy on EC2
        run: |
          ssh -i ~/.ssh/winston-aws-vm-key -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/services/task-tracker
            docker compose pull
            docker compose down
            docker compose up -d
          EOF
